"""Composite vault-health view (ARC-005).

Extracted from ``vault_stats.py``. ``run_health`` is a thin wrapper over
the ``vault_health`` scoring module that handles JSON vs. plain-text
output and the ``--fast`` metadata-skip flag.
"""

from __future__ import annotations

from pathlib import Path

from cli.stats._common import _get_console


def run_health(
    vault: Path | None = None, *, as_json: bool = False, fast: bool = False
) -> None:
    """Print the composite vault health report (ENH-007).

    The report is generated by ``vault_health`` (stdlib-only scoring module).
    This wrapper handles JSON vs. plain-text output and the ``--fast`` skip.

    Args:
        vault: Optional vault path. Defaults to ``resolve_vault()``.
        as_json: When True, emit the report as compact JSON on stdout
            (consumed by the MCP server and the visualizer). When False,
            print the rendered plain-text report via Rich.
        fast: When True, skip the metadata-quality scan so the report renders
            in well under a second on large vaults. The metadata dimension
            reports "skipped (--fast)" with a neutral score.
    """
    import vault_health

    report = vault_health.compute_health_report(vault, skip_metadata=fast)
    if as_json:
        # Plain print, not Rich, so the byte stream is parseable JSON.
        print(vault_health.to_json(report))
        return
    # Render through Rich so the report respects the same theme/width as the
    # other modes; the renderer itself emits no Rich markup.
    _get_console().print(vault_health.render_report(report))
