"""vault_index -- compatibility shim (ARC-004).

Implementation moved to ``core.vault_index``. This shim re-exports the
module's complete non-dunder surface so every existing caller --
``import vault_index``, ``from vault_index import X``, ``vault_index.X`` (hooks, CLIs,
tests, parsidion-mcp, the installer) -- keeps working unchanged,
including imported constants and test monkeypatch targets. The
stdlib-only constraint is enforced on ``core.vault_index`` by
``tests/test_stdlib_only.py``.
"""

from core.vault_index import (  # noqa: F401 -- full-surface re-export
    Any,
    EXCLUDE_DIRS,
    Path,
    VAULT_DIRS,
    _FRONTMATTER_RE,
    _PARSE_WARNINGS_MAX,
    _SLUG_MULTI_HYPHEN_RE,
    _SLUG_SPECIAL_RE,
    _YAML_LIST_INLINE_RE,
    _find_notes_by_field,
    _load_note_index_map,
    _parse_list_item,
    _parse_scalar,
    _parse_warnings,
    _split_list_items,
    _walk_vault_notes,
    all_vault_notes,
    annotations,
    build_compact_index,
    build_context_block,
    datetime,
    drain_parse_warnings,
    ensure_note_index_schema,
    extract_title,
    find_notes_by_project,
    find_notes_by_tag,
    find_notes_by_type,
    find_recent_notes,
    get_body,
    get_embeddings_db_path,
    hashlib,
    is_path_inside_vault,
    is_symlink_inside_vault,
    load_graph_metadata,
    os,
    parse_frontmatter,
    parse_related_stems,
    query_note_index,
    re,
    read_note_summary,
    record_parse_warning,
    resolve_vault,
    slugify,
    sqlite3,
    sys,
    timedelta,
    unicodedata,
)
