"""Markdown rendering for TAGS.md and per-folder MANIFEST.md (ARC-005).

Extracted from ``update_index.py``. Re-exported by the entry shim so
``update_index.build_tags_md`` and ``update_index.build_manifests`` keep
resolving for tests and other callers.

Stdlib-only at module load.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime
from pathlib import Path

from vault_fs import atomic_write_text

from cli.index.parse import _WIKILINK_RE


def build_tags_md(tag_counter: Counter[str], now_str: str) -> str:
    """Build the TAGS.md content with the full tag cloud and tag list.

    Args:
        tag_counter: Tag frequency counter from build_index().
        now_str: Timestamp string for the header.

    Returns:
        Complete TAGS.md file content.
    """
    lines: list[str] = []
    lines.append("# Vault Tags")
    lines.append("")
    lines.append(f"> Auto-generated by update_index.py on {now_str}")
    lines.append("> Do not edit manually - changes will be overwritten")
    lines.append("")

    # Tag Cloud (human-readable, sorted by frequency)
    lines.append("## Tag Cloud")
    if tag_counter:
        tag_parts: list[str] = []
        for tag, count in tag_counter.most_common():
            tag_parts.append(f"`{tag}` ({count})")
        lines.append(" | ".join(tag_parts))
    else:
        lines.append("_No tags found._")
    lines.append("")

    # Existing Tags (machine-readable for the AI summarizer)
    lines.append("## Existing Tags")
    if tag_counter:
        lines.append(", ".join(sorted(tag_counter.keys())))
    else:
        lines.append("")
    lines.append("")

    return "\n".join(lines)


def build_manifests(
    folder_notes: dict[str, list[tuple[str, str, str, list[str], bool]]],
    vault: Path,
) -> list[Path]:
    """Generate a MANIFEST.md file inside each non-empty vault subfolder.

    Each manifest contains a Markdown table with one row per note, showing the
    note stem as a wikilink, its tags, and a one-line summary. Stale notes are
    marked with a warning emoji in the Note column.

    Args:
        folder_notes: Mapping from folder name to list of
            (wikilink, title, summary, tags, is_stale) tuples, as returned by
            ``build_index()``.

    Returns:
        A list of Path objects for all MANIFEST.md files written.
    """
    now_str: str = datetime.now().strftime("%Y-%m-%d %H:%M")
    written: list[Path] = []

    for folder_name, entries in folder_notes.items():
        if not entries:
            continue

        folder_dir: Path = vault / folder_name
        if not folder_dir.is_dir():
            continue

        note_count: int = len(entries)
        lines: list[str] = []
        lines.append(f"# {folder_name} — Vault Notes ({note_count} notes)")
        lines.append(
            f"<!-- Auto-generated by update_index.py on {now_str} — do not edit manually -->"
        )
        lines.append("")
        lines.append("| Note | Tags | Summary |")
        lines.append("|------|------|---------|")

        for wlink, _title, summary, tags, is_stale in entries:
            # wlink is like [[stem]] — extract stem for display
            stem_match = _WIKILINK_RE.match(wlink)
            stem: str = stem_match.group(1) if stem_match else wlink

            stale_prefix: str = "⚠️ " if is_stale else ""
            note_cell: str = f"{stale_prefix}[[{stem}]]"

            tags_cell: str = " ".join(f"`{t}`" for t in tags) if tags else ""
            # Escape pipe characters in summary to avoid breaking the table
            summary_cell: str = summary.replace("|", "\\|") if summary else ""

            lines.append(f"| {note_cell} | {tags_cell} | {summary_cell} |")

        lines.append("")
        content: str = "\n".join(lines)

        manifest_path: Path = folder_dir / "MANIFEST.md"
        # QA-017: route through atomic_write_text so an interrupt cannot
        # leave a half-written MANIFEST.md (the index regenerates these, but
        # a truncated file is still a confusing experience mid-rebuild).
        atomic_write_text(manifest_path, content)
        written.append(manifest_path)

    return written
